/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthResponseDto,
  CoinDto,
  LoginRequestDto,
  OrderCreateDto,
  OrderDto,
  PortfolioDto,
  PortfolioItemDto,
  SignupRequestDto,
  WalletRequestDto,
  WalletResponseDto,
} from '../models/index';
import {
    AuthResponseDtoFromJSON,
    AuthResponseDtoToJSON,
    CoinDtoFromJSON,
    CoinDtoToJSON,
    LoginRequestDtoFromJSON,
    LoginRequestDtoToJSON,
    OrderCreateDtoFromJSON,
    OrderCreateDtoToJSON,
    OrderDtoFromJSON,
    OrderDtoToJSON,
    PortfolioDtoFromJSON,
    PortfolioDtoToJSON,
    PortfolioItemDtoFromJSON,
    PortfolioItemDtoToJSON,
    SignupRequestDtoFromJSON,
    SignupRequestDtoToJSON,
    WalletRequestDtoFromJSON,
    WalletRequestDtoToJSON,
    WalletResponseDtoFromJSON,
    WalletResponseDtoToJSON,
} from '../models/index';

export interface CoinIdGetRequest {
    id: string;
}

export interface CreateOrderRequest {
    orderCreateDto: OrderCreateDto;
}

export interface CreateUserRequest {
    signupRequestDto: SignupRequestDto;
}

export interface LoginUserRequest {
    loginRequestDto: LoginRequestDto;
}

export interface PatchWalletRequest {
    walletRequestDto: WalletRequestDto;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get a specific coin by ID
     */
    async coinIdGetRaw(requestParameters: CoinIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoinDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling coinIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/coin/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoinDtoFromJSON(jsonValue));
    }

    /**
     * Get a specific coin by ID
     */
    async coinIdGet(requestParameters: CoinIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoinDto> {
        const response = await this.coinIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new order
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDto>> {
        if (requestParameters['orderCreateDto'] == null) {
            throw new runtime.RequiredError(
                'orderCreateDto',
                'Required parameter "orderCreateDto" was null or undefined when calling createOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/order`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderCreateDtoToJSON(requestParameters['orderCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDtoFromJSON(jsonValue));
    }

    /**
     * Create a new order
     */
    async createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDto> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * User signup
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponseDto>> {
        if (requestParameters['signupRequestDto'] == null) {
            throw new runtime.RequiredError(
                'signupRequestDto',
                'Required parameter "signupRequestDto" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestDtoToJSON(requestParameters['signupRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseDtoFromJSON(jsonValue));
    }

    /**
     * User signup
     */
    async createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponseDto> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user orders
     */
    async getMyOrdersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OrderDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderDtoFromJSON));
    }

    /**
     * Get user orders
     */
    async getMyOrders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OrderDto>> {
        const response = await this.getMyOrdersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get portfolio items
     */
    async getPortfolioItemsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PortfolioItemDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/portfolio/items`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PortfolioItemDtoFromJSON));
    }

    /**
     * Get portfolio items
     */
    async getPortfolioItems(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PortfolioItemDto>> {
        const response = await this.getPortfolioItemsRaw(initOverrides);
        return await response.value();
    }

    /**
     * User login
     */
    async loginUserRaw(requestParameters: LoginUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponseDto>> {
        if (requestParameters['loginRequestDto'] == null) {
            throw new runtime.RequiredError(
                'loginRequestDto',
                'Required parameter "loginRequestDto" was null or undefined when calling loginUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestDtoToJSON(requestParameters['loginRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseDtoFromJSON(jsonValue));
    }

    /**
     * User login
     */
    async loginUser(requestParameters: LoginUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponseDto> {
        const response = await this.loginUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add or withdraw money to/from wallet
     */
    async patchWalletRaw(requestParameters: PatchWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponseDto>> {
        if (requestParameters['walletRequestDto'] == null) {
            throw new runtime.RequiredError(
                'walletRequestDto',
                'Required parameter "walletRequestDto" was null or undefined when calling patchWallet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/wallet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletRequestDtoToJSON(requestParameters['walletRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseDtoFromJSON(jsonValue));
    }

    /**
     * Add or withdraw money to/from wallet
     */
    async patchWallet(requestParameters: PatchWalletRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponseDto> {
        const response = await this.patchWalletRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of all coins
     */
    async readCoinsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CoinDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/coin`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CoinDtoFromJSON));
    }

    /**
     * Get list of all coins
     */
    async readCoins(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CoinDto>> {
        const response = await this.readCoinsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user portfolio
     */
    async readPortfolioRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/portfolio`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioDtoFromJSON(jsonValue));
    }

    /**
     * Get user portfolio
     */
    async readPortfolio(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioDto> {
        const response = await this.readPortfolioRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get wallet balance
     */
    async readWalletRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/wallet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get wallet balance
     */
    async readWallet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletResponseDto> {
        const response = await this.readWalletRaw(initOverrides);
        return await response.value();
    }

}
