/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponseDto
 */
export interface AuthResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    jwt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponseDto
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponseDto
     */
    isTwoFactorAuthEnabled?: boolean;
    /**
     * 
     * @type {any}
     * @memberof AuthResponseDto
     */
    session?: any | null;
}

/**
 * Check if a given object implements the AuthResponseDto interface.
 */
export function instanceOfAuthResponseDto(value: object): value is AuthResponseDto {
    return true;
}

export function AuthResponseDtoFromJSON(json: any): AuthResponseDto {
    return AuthResponseDtoFromJSONTyped(json, false);
}

export function AuthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jwt': json['jwt'] == null ? undefined : json['jwt'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'isTwoFactorAuthEnabled': json['isTwoFactorAuthEnabled'] == null ? undefined : json['isTwoFactorAuthEnabled'],
        'session': json['session'] == null ? undefined : json['session'],
    };
}

export function AuthResponseDtoToJSON(json: any): AuthResponseDto {
    return AuthResponseDtoToJSONTyped(json, false);
}

export function AuthResponseDtoToJSONTyped(value?: AuthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jwt': value['jwt'],
        'status': value['status'],
        'message': value['message'],
        'isTwoFactorAuthEnabled': value['isTwoFactorAuthEnabled'],
        'session': value['session'],
    };
}

