/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoinDto
 */
export interface CoinDto {
    /**
     * 
     * @type {string}
     * @memberof CoinDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CoinDto
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof CoinDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CoinDto
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    currentPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    marketCap?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    marketCapRank?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    fullyDilutedValuation?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    totalVolume?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    high24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    low24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    priceChange24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    priceChangePercentage24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    marketCapChange24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    marketCapChangePercentage24h?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    circulatingSupply?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    totalSupply?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    maxSupply?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    ath?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    athChangePercentage?: number;
    /**
     * 
     * @type {Date}
     * @memberof CoinDto
     */
    athDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    atl?: number;
    /**
     * 
     * @type {number}
     * @memberof CoinDto
     */
    atlChangePercentage?: number;
    /**
     * 
     * @type {Date}
     * @memberof CoinDto
     */
    atlDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CoinDto
     */
    lastUpdated?: Date;
}

/**
 * Check if a given object implements the CoinDto interface.
 */
export function instanceOfCoinDto(value: object): value is CoinDto {
    return true;
}

export function CoinDtoFromJSON(json: any): CoinDto {
    return CoinDtoFromJSONTyped(json, false);
}

export function CoinDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoinDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'currentPrice': json['current_price'] == null ? undefined : json['current_price'],
        'marketCap': json['market_cap'] == null ? undefined : json['market_cap'],
        'marketCapRank': json['market_cap_rank'] == null ? undefined : json['market_cap_rank'],
        'fullyDilutedValuation': json['fully_diluted_valuation'] == null ? undefined : json['fully_diluted_valuation'],
        'totalVolume': json['total_volume'] == null ? undefined : json['total_volume'],
        'high24h': json['high_24h'] == null ? undefined : json['high_24h'],
        'low24h': json['low_24h'] == null ? undefined : json['low_24h'],
        'priceChange24h': json['price_change_24h'] == null ? undefined : json['price_change_24h'],
        'priceChangePercentage24h': json['price_change_percentage_24h'] == null ? undefined : json['price_change_percentage_24h'],
        'marketCapChange24h': json['market_cap_change_24h'] == null ? undefined : json['market_cap_change_24h'],
        'marketCapChangePercentage24h': json['market_cap_change_percentage_24h'] == null ? undefined : json['market_cap_change_percentage_24h'],
        'circulatingSupply': json['circulating_supply'] == null ? undefined : json['circulating_supply'],
        'totalSupply': json['total_supply'] == null ? undefined : json['total_supply'],
        'maxSupply': json['max_supply'] == null ? undefined : json['max_supply'],
        'ath': json['ath'] == null ? undefined : json['ath'],
        'athChangePercentage': json['ath_change_percentage'] == null ? undefined : json['ath_change_percentage'],
        'athDate': json['ath_date'] == null ? undefined : (new Date(json['ath_date'])),
        'atl': json['atl'] == null ? undefined : json['atl'],
        'atlChangePercentage': json['atl_change_percentage'] == null ? undefined : json['atl_change_percentage'],
        'atlDate': json['atl_date'] == null ? undefined : (new Date(json['atl_date'])),
        'lastUpdated': json['last_updated'] == null ? undefined : (new Date(json['last_updated'])),
    };
}

export function CoinDtoToJSON(json: any): CoinDto {
    return CoinDtoToJSONTyped(json, false);
}

export function CoinDtoToJSONTyped(value?: CoinDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'symbol': value['symbol'],
        'name': value['name'],
        'image': value['image'],
        'current_price': value['currentPrice'],
        'market_cap': value['marketCap'],
        'market_cap_rank': value['marketCapRank'],
        'fully_diluted_valuation': value['fullyDilutedValuation'],
        'total_volume': value['totalVolume'],
        'high_24h': value['high24h'],
        'low_24h': value['low24h'],
        'price_change_24h': value['priceChange24h'],
        'price_change_percentage_24h': value['priceChangePercentage24h'],
        'market_cap_change_24h': value['marketCapChange24h'],
        'market_cap_change_percentage_24h': value['marketCapChangePercentage24h'],
        'circulating_supply': value['circulatingSupply'],
        'total_supply': value['totalSupply'],
        'max_supply': value['maxSupply'],
        'ath': value['ath'],
        'ath_change_percentage': value['athChangePercentage'],
        'ath_date': value['athDate'] == null ? undefined : ((value['athDate']).toISOString()),
        'atl': value['atl'],
        'atl_change_percentage': value['atlChangePercentage'],
        'atl_date': value['atlDate'] == null ? undefined : ((value['atlDate']).toISOString()),
        'last_updated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
    };
}

