/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    coinId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    status?: string;
}

/**
 * Check if a given object implements the OrderDto interface.
 */
export function instanceOfOrderDto(value: object): value is OrderDto {
    return true;
}

export function OrderDtoFromJSON(json: any): OrderDto {
    return OrderDtoFromJSONTyped(json, false);
}

export function OrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'coinId': json['coinId'] == null ? undefined : json['coinId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function OrderDtoToJSON(json: any): OrderDto {
    return OrderDtoToJSONTyped(json, false);
}

export function OrderDtoToJSONTyped(value?: OrderDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'coinId': value['coinId'],
        'quantity': value['quantity'],
        'price': value['price'],
        'type': value['type'],
        'status': value['status'],
    };
}

