/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
    AssetToJSONTyped,
} from './Asset';

/**
 * 
 * @export
 * @interface PortfolioDto
 */
export interface PortfolioDto {
    /**
     * 
     * @type {string}
     * @memberof PortfolioDto
     */
    id?: string;
    /**
     * 
     * @type {Array<Asset>}
     * @memberof PortfolioDto
     */
    assets?: Array<Asset>;
}

/**
 * Check if a given object implements the PortfolioDto interface.
 */
export function instanceOfPortfolioDto(value: object): value is PortfolioDto {
    return true;
}

export function PortfolioDtoFromJSON(json: any): PortfolioDto {
    return PortfolioDtoFromJSONTyped(json, false);
}

export function PortfolioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'assets': json['assets'] == null ? undefined : ((json['assets'] as Array<any>).map(AssetFromJSON)),
    };
}

export function PortfolioDtoToJSON(json: any): PortfolioDto {
    return PortfolioDtoToJSONTyped(json, false);
}

export function PortfolioDtoToJSONTyped(value?: PortfolioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'assets': value['assets'] == null ? undefined : ((value['assets'] as Array<any>).map(AssetToJSON)),
    };
}

