/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortfolioItemDto } from './PortfolioItemDto';
import {
    PortfolioItemDtoFromJSON,
    PortfolioItemDtoFromJSONTyped,
    PortfolioItemDtoToJSON,
    PortfolioItemDtoToJSONTyped,
} from './PortfolioItemDto';

/**
 * 
 * @export
 * @interface PortfolioDto
 */
export interface PortfolioDto {
    /**
     * 
     * @type {string}
     * @memberof PortfolioDto
     */
    id?: string;
    /**
     * 
     * @type {Array<PortfolioItemDto>}
     * @memberof PortfolioDto
     */
    portfolioItems?: Array<PortfolioItemDto>;
}

/**
 * Check if a given object implements the PortfolioDto interface.
 */
export function instanceOfPortfolioDto(value: object): value is PortfolioDto {
    return true;
}

export function PortfolioDtoFromJSON(json: any): PortfolioDto {
    return PortfolioDtoFromJSONTyped(json, false);
}

export function PortfolioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'portfolioItems': json['portfolioItems'] == null ? undefined : ((json['portfolioItems'] as Array<any>).map(PortfolioItemDtoFromJSON)),
    };
}

export function PortfolioDtoToJSON(json: any): PortfolioDto {
    return PortfolioDtoToJSONTyped(json, false);
}

export function PortfolioDtoToJSONTyped(value?: PortfolioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'portfolioItems': value['portfolioItems'] == null ? undefined : ((value['portfolioItems'] as Array<any>).map(PortfolioItemDtoToJSON)),
    };
}

