/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletResponseDto
 */
export interface WalletResponseDto {
    /**
     * 
     * @type {string}
     * @memberof WalletResponseDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletResponseDto
     */
    balance?: number;
}

/**
 * Check if a given object implements the WalletResponseDto interface.
 */
export function instanceOfWalletResponseDto(value: object): value is WalletResponseDto {
    return true;
}

export function WalletResponseDtoFromJSON(json: any): WalletResponseDto {
    return WalletResponseDtoFromJSONTyped(json, false);
}

export function WalletResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'balance': json['balance'] == null ? undefined : json['balance'],
    };
}

export function WalletResponseDtoToJSON(json: any): WalletResponseDto {
    return WalletResponseDtoToJSONTyped(json, false);
}

export function WalletResponseDtoToJSONTyped(value?: WalletResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'balance': value['balance'],
    };
}

