/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequestDto
 */
export interface SignupRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestDto
     */
    password: string;
}

/**
 * Check if a given object implements the SignupRequestDto interface.
 */
export function instanceOfSignupRequestDto(value: object): value is SignupRequestDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignupRequestDtoFromJSON(json: any): SignupRequestDto {
    return SignupRequestDtoFromJSONTyped(json, false);
}

export function SignupRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function SignupRequestDtoToJSON(json: any): SignupRequestDto {
    return SignupRequestDtoToJSONTyped(json, false);
}

export function SignupRequestDtoToJSONTyped(value?: SignupRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
    };
}

