/* tslint:disable */
/* eslint-disable */
/**
 * Auth & CoinInfo API
 * API for authentication and coin data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletRequestDto
 */
export interface WalletRequestDto {
    /**
     * 
     * @type {string}
     * @memberof WalletRequestDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof WalletRequestDto
     */
    balance?: number;
}

/**
 * Check if a given object implements the WalletRequestDto interface.
 */
export function instanceOfWalletRequestDto(value: object): value is WalletRequestDto {
    return true;
}

export function WalletRequestDtoFromJSON(json: any): WalletRequestDto {
    return WalletRequestDtoFromJSONTyped(json, false);
}

export function WalletRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'balance': json['balance'] == null ? undefined : json['balance'],
    };
}

export function WalletRequestDtoToJSON(json: any): WalletRequestDto {
    return WalletRequestDtoToJSONTyped(json, false);
}

export function WalletRequestDtoToJSONTyped(value?: WalletRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'balance': value['balance'],
    };
}

